-- MySQL Script generated by MySQL Workbench
-- Mon Aug 14 19:55:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oficina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oficina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oficina` DEFAULT CHARACTER SET utf8 ;
USE `oficina` ;

-- -----------------------------------------------------
-- Table `oficina`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `telefone_cliente` CHAR(11) NOT NULL,
  `email_cliente` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`veiculo` (
  `idveiculo` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(20) NULL,
  `modelo` VARCHAR(20) NULL,
  `ano` CHAR(4) NULL,
  `categoria` VARCHAR(20) NULL,
  `placa` CHAR(7) NULL,
  `fk_idcliente` INT NOT NULL,
  PRIMARY KEY (`idveiculo`),
  INDEX `fk_Veiculo_Cliente1_idx` (`fk_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Cliente1`
    FOREIGN KEY (`fk_idcliente`)
    REFERENCES `oficina`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`equipe` (
  `idequipe` INT NOT NULL AUTO_INCREMENT,
  `especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idequipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`avaliacao` (
  `idavaliacao` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `validade` DATE NULL,
  `descrição_queixa` VARCHAR(45) NULL,
  `fk_idveiculo` INT NOT NULL,
  `fk_idequipe` INT NOT NULL,
  PRIMARY KEY (`idavaliacao`),
  INDEX `fk_Avaliação_Veiculo1_idx` (`fk_idveiculo` ASC) VISIBLE,
  INDEX `fk_Avaliação_Equipe1_idx` (`fk_idequipe` ASC) VISIBLE,
  CONSTRAINT `fk_Avaliação_Veiculo1`
    FOREIGN KEY (`fk_idveiculo`)
    REFERENCES `oficina`.`veiculo` (`idveiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliação_Equipe1`
    FOREIGN KEY (`fk_idequipe`)
    REFERENCES `oficina`.`equipe` (`idequipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`ordem_de_serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`ordem_de_servico` (
  `idordem_de_servico` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('Em andamento', 'Concluído') NOT NULL,
  `fk_idavaliacao` INT NOT NULL,
  PRIMARY KEY (`idordem_de_servico`),
  INDEX `fk_Ordem de serviço_Avaliação1_idx` (`fk_idavaliacao` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de serviço_Avaliação1`
    FOREIGN KEY (`fk_idavaliacao`)
    REFERENCES `oficina`.`avaliacao` (`idavaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`servicos` (
  `idservico` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`idservico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`pecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`pecas` (
  `idpecas` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`idpecas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`pagamento` (
  `idpagamento` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('APROVADO', 'PENDENTE') NULL,
  `valor` FLOAT NULL,
  `fk_idcliente` INT NOT NULL,
  `fk_idordem_de_servico` INT NOT NULL,
  PRIMARY KEY (`idpagamento`),
  INDEX `fk_Pagamento_Cliente1_idx` (`fk_idcliente` ASC) VISIBLE,
  INDEX `fk_Pagamento_Ordem de serviço1_idx` (`fk_idordem_de_servico` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Cliente1`
    FOREIGN KEY (`fk_idcliente`)
    REFERENCES `oficina`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamento_Ordem de serviço1`
    FOREIGN KEY (`fk_idordem_de_servico`)
    REFERENCES `oficina`.`ordem_de_serviço` (`idordem_de_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`os_pecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`os_pecas` (
  `fk_idordem_de_servico` INT NOT NULL,
  `fk_idpecas` INT NOT NULL,
  `quantidade` INT NULL,
  INDEX `fk_Ordem de serviço_has_Peças_Peças1_idx` (`fk_idpecas` ASC) VISIBLE,
  INDEX `fk_Ordem de serviço_has_Peças_Ordem de serviço1_idx` (`fk_idordem_de_servico` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de serviço_has_Peças_Ordem de serviço1`
    FOREIGN KEY (`fk_idordem_de_servico`)
    REFERENCES `oficina`.`ordem_de_serviço` (`idordem_de_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de serviço_has_Peças_Peças1`
    FOREIGN KEY (`fk_idpecas`)
    REFERENCES `oficina`.`pecas` (`idpecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`os_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`os_servicos` (
  `fk_idordem_de_servico` INT NOT NULL,
  `fk_idservico` INT NOT NULL,
  INDEX `fk_Ordem de serviço_has_Mão de obra_Mão de obra1_idx` (`fk_idservico` ASC) VISIBLE,
  INDEX `fk_Ordem de serviço_has_Mão de obra_Ordem de serviço1_idx` (`fk_idordem_de_servico` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de serviço_has_Mão de obra_Ordem de serviço1`
    FOREIGN KEY (`fk_idordem_de_servico`)
    REFERENCES `oficina`.`ordem_de_serviço` (`idordem_de_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de serviço_has_Mão de obra_Mão de obra1`
    FOREIGN KEY (`fk_idservico`)
    REFERENCES `oficina`.`servicos` (`idservico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
