-- MySQL Script generated by MySQL Workbench
-- Mon Aug  7 12:24:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NULL DEFAULT NULL,
  `cpf_cnpj` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`fornecedor` (
  `idfornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome_fantasia` VARCHAR(45) NOT NULL,
  `razao_social` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(14) NULL DEFAULT NULL,
  PRIMARY KEY (`idfornecedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(30) NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  `valor` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`disponibiliza_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`disponibiliza_produto` (
  `fk_idfornecedor` INT NOT NULL,
  `fk_idproduto` INT NOT NULL,
  INDEX `fk_idfornecedor` (`fk_idfornecedor` ASC) VISIBLE,
  INDEX `fk_idproduto` (`fk_idproduto` ASC) VISIBLE,
  CONSTRAINT `disponibiliza_produto_ibfk_1`
    FOREIGN KEY (`fk_idfornecedor`)
    REFERENCES `ecommerce`.`fornecedor` (`idfornecedor`),
  CONSTRAINT `disponibiliza_produto_ibfk_2`
    FOREIGN KEY (`fk_idproduto`)
    REFERENCES `ecommerce`.`produto` (`idproduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`endereco` (
  `logradouro` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(30) NOT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `fk_idcliente` INT NOT NULL,
  INDEX `fk_idcliente` (`fk_idcliente` ASC) VISIBLE,
  CONSTRAINT `endereco_ibfk_1`
    FOREIGN KEY (`fk_idcliente`)
    REFERENCES `ecommerce`.`cliente` (`idcliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`entrega` (
  `identrega` INT NOT NULL AUTO_INCREMENT,
  `cod_rastreio` VARCHAR(45) NULL DEFAULT NULL,
  `status_entrega` ENUM('A ENVIAR', 'EM ROTA', 'ENTREGUE', 'CANCELADO') NOT NULL,
  PRIMARY KEY (`identrega`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`estoque` (
  `idestoque` INT NOT NULL AUTO_INCREMENT,
  `local` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idestoque`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`pagamento` (
  `idpagamento` INT NOT NULL AUTO_INCREMENT,
  `tipo_pagamento` ENUM('AVISTA', 'CARTAO', 'PIX') NOT NULL,
  `status_pagamento` ENUM('APROVADO', 'PENDENTE', 'CANCELADO') NOT NULL COMMENT 'Status \'A\' para pagamento aprovado. Status \'P\' para pagamento pendente. ',
  PRIMARY KEY (`idpagamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `status_pedido` ENUM('Em andamento', 'Concluído', 'Cancelado') NOT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `fk_idcliente` INT NOT NULL,
  `frete` FLOAT NULL DEFAULT NULL,
  `fk_idpagamento` INT NOT NULL,
  `fk_identrega` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_idcliente` (`fk_idcliente` ASC) VISIBLE,
  INDEX `fk_idpagamento` (`fk_idpagamento` ASC) VISIBLE,
  INDEX `fk_identrega` (`fk_identrega` ASC) VISIBLE,
  CONSTRAINT `pedido_ibfk_1`
    FOREIGN KEY (`fk_idcliente`)
    REFERENCES `ecommerce`.`cliente` (`idcliente`),
  CONSTRAINT `pedido_ibfk_2`
    FOREIGN KEY (`fk_idpagamento`)
    REFERENCES `ecommerce`.`pagamento` (`idpagamento`),
  CONSTRAINT `pedido_ibfk_3`
    FOREIGN KEY (`fk_identrega`)
    REFERENCES `ecommerce`.`entrega` (`identrega`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`produto_has_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`produto_has_estoque` (
  `fk_idproduto` INT NOT NULL,
  `fk_idestoque` INT NOT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  INDEX `fk_idproduto` (`fk_idproduto` ASC) VISIBLE,
  INDEX `fk_idestoque` (`fk_idestoque` ASC) VISIBLE,
  CONSTRAINT `produto_has_estoque_ibfk_1`
    FOREIGN KEY (`fk_idproduto`)
    REFERENCES `ecommerce`.`produto` (`idproduto`),
  CONSTRAINT `produto_has_estoque_ibfk_2`
    FOREIGN KEY (`fk_idestoque`)
    REFERENCES `ecommerce`.`estoque` (`idestoque`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`relacao_produto_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`relacao_produto_pedido` (
  `fk_idProduto` INT NOT NULL,
  `fk_idPedido` INT NOT NULL,
  `quantidade` INT NOT NULL,
  INDEX `fk_idProduto` (`fk_idProduto` ASC) VISIBLE,
  INDEX `fk_idPedido` (`fk_idPedido` ASC) VISIBLE,
  CONSTRAINT `relacao_produto_pedido_ibfk_1`
    FOREIGN KEY (`fk_idProduto`)
    REFERENCES `ecommerce`.`produto` (`idproduto`),
  CONSTRAINT `relacao_produto_pedido_ibfk_2`
    FOREIGN KEY (`fk_idPedido`)
    REFERENCES `ecommerce`.`pedido` (`idpedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`terceiro_vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`terceiro_vendedor` (
  `idTerceirovendedor` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(45) NULL DEFAULT NULL,
  `cnpj` VARCHAR(14) NULL DEFAULT NULL,
  `local` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTerceirovendedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`terceiro_vendedor_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`terceiro_vendedor_has_produto` (
  `fk_idTerceirovendedor` INT NOT NULL,
  `fk_idproduto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  INDEX `fk_idTerceirovendedor` (`fk_idTerceirovendedor` ASC) VISIBLE,
  INDEX `fk_idproduto` (`fk_idproduto` ASC) VISIBLE,
  CONSTRAINT `terceiro_vendedor_has_produto_ibfk_1`
    FOREIGN KEY (`fk_idTerceirovendedor`)
    REFERENCES `ecommerce`.`terceiro_vendedor` (`idTerceirovendedor`),
  CONSTRAINT `terceiro_vendedor_has_produto_ibfk_2`
    FOREIGN KEY (`fk_idproduto`)
    REFERENCES `ecommerce`.`produto` (`idproduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
